descriptor_extension: yml
package:
  description: SONATA vCDN
  maintainer: Felipe Vicens, ATOS, felipe.vicens@atos.net
  name: "sonata-vcdn-vtc-only"
  vendor: "eu.sonata-nfv"
  version: "0.1"
version: '0.5'
