descriptor_extension: yml
package:
  description: SONATA vCDN PLACEMENT SSM
  maintainer: Felipe Vicens, ATOS, felipe.vicens@atos.net
  name: "son-vcdn-placementssm"
  vendor: "eu.sonata-nfv"
  version: "0.1"
version: '0.5'
