descriptor_extension: yml
package:
  description: SONATA vCDN SSM
  maintainer: Felipe Vicens, ATOS, felipe.vicens@atos.net
  name: "son-vcdn-ssm"
  vendor: "eu.sonata-nfv"
  version: "0.1"
version: '0.5'
